# Copyright 2023 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
all:
  hosts:
    srlinux:
      ansible_host: clab-IXP-Peering-srlinux
      ansible_user: admin
      ansible_ssh_pass: NokiaSrl1!
      bgp:
        neighbors:
          - name: sros
            # as: xyz # could specify AS here instead

    sros:
      ansible_host: clab-IXP-Peering-sros
      ansible_user: admin
      ansible_ssh_pass: admin
      bgp:
        neighbors:
          - name: srlinux

    ixp:
      ansible_host: clab-IXP-Peering-ixp
