# Copyright 2026 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# --- ARTIFACTS ---
apiVersion: artifacts.eda.nokia.com/v1
kind: Artifact
metadata:
  name: clab-srlinux-26.7.2
  namespace: eda-system
spec:
  filePath: srlinux-26.7.2.zip
  remoteFileUrl:
    fileUrl: "https://github.com/nokia-eda/schema-profiles/releases/download/nokia-srl-26.7.2/srlinux-26.7.2-519.zip"
  repo: clab-schemaprofiles
---
apiVersion: artifacts.eda.nokia.com/v1
kind: Artifact
metadata:
  name: clab-llm-db-srlinux-26.7.2
  namespace: eda-system
spec:
  filePath: llm-embeddings-srl-26-7-2.tar.gz
  remoteFileUrl:
    fileUrl: "https://github.com/nokia-eda/llm-embeddings/releases/download/nokia-srl-26.7.2/llm-embeddings-srl-26-7-2-v1.tar.gz"
  repo: clab-llm-dbs
---

# --- INIT ---
apiVersion: bootstrap.eda.nokia.com/v1
kind: Init
metadata:
  name: init-base
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  commitSave: true
  mgmt:
    staticRoutes:
      - nextHop: 10.128.${INSTANCE_ID}.1
        prefix: 0.0.0.0/0
  nodeSelectors:
    - containerlab=managed
---

# --- NODE-USER-GROUP ---
apiVersion: aaa.eda.nokia.com/v1
kind: NodeGroup
metadata:
  name: sudo
  namespace: eda
spec:
  rules: []
  services:
    - GNMI
    - CLI
    - NETCONF
    - GNOI
    - GNSI
  superuser: true
---

# --- NODE-USER ---
apiVersion: core.eda.nokia.com/v1
kind: NodeUser
metadata:
  name: admin
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  username: admin
  password: ${EVENT_PASSWORD}
  groupBindings:
    - groups:
        - sudo
      nodeSelector:
        - containerlab=managed
  sshPublicKeys:
    - ${SSH_PUBLIC_KEY}
---

# --- NODE-PROFILES ---
apiVersion: core.eda.nokia.com/v1
kind: NodeProfile
metadata:
  name: hackathon-srlinux-26.7.2
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  port: 57410
  annotate: true
  operatingSystem: srl
  version: 26.7.2
  versionPath: .system.information.version
  versionMatch: v26\.7\.2.*
  llmDb: https://eda-asvr.eda-system.svc/_base_/clab-llm-dbs/clab-llm-db-srlinux-26.7.2/llm-embeddings-srl-26-7-2.tar.gz
  yang: https://eda-asvr.eda-system.svc/_base_/clab-schemaprofiles/clab-srlinux-26.7.2/srlinux-26.7.2.zip
  nodeUser: admin
  onboardingPassword: NokiaSrl1!
  onboardingUsername: admin
  images:
    - image: fake.bin
      imageMd5: fake.bin.md5
  containerImage: ghcr.io/nokia/srlinux:26.7.2-519
  imagePullSecret: core
  license: cx-srl-26-7-1-ghcr-license
---

# --- TOPONODES ---
apiVersion: core.eda.nokia.com/v1
kind: TopoNode
metadata:
  name: g${INSTANCE_ID}-leaf11
  labels:
    eda.nokia.com/role: leaf
    eda.nokia.com/security-profile: managed
    containerlab: managed
    role: hackathon-infra
  namespace: eda
spec:
  nodeProfile: hackathon-srlinux-26.7.2
  npp:
    mode: normal
  operatingSystem: srl
  platform: 7220 IXR-D3L
  version: 26.7.2
  productionAddress:
    ipv4: 10.128.${INSTANCE_ID}.33/24
---
apiVersion: core.eda.nokia.com/v1
kind: TopoNode
metadata:
  name: g${INSTANCE_ID}-leaf12
  labels:
    eda.nokia.com/role: leaf
    eda.nokia.com/security-profile: managed
    containerlab: managed
    role: hackathon-infra
  namespace: eda
spec:
  nodeProfile: hackathon-srlinux-26.7.2
  npp:
    mode: normal
  operatingSystem: srl
  platform: 7220 IXR-D3L
  version: 26.7.2
  productionAddress:
    ipv4: 10.128.${INSTANCE_ID}.34/24
---
apiVersion: core.eda.nokia.com/v1
kind: TopoNode
metadata:
  name: g${INSTANCE_ID}-leaf13
  labels:
    eda.nokia.com/role: leaf
    eda.nokia.com/security-profile: managed
    containerlab: managed
    role: hackathon-infra
  namespace: eda
spec:
  nodeProfile: hackathon-srlinux-26.7.2
  npp:
    mode: normal
  operatingSystem: srl
  platform: 7220 IXR-D3L
  version: 26.7.2
  productionAddress:
    ipv4: 10.128.${INSTANCE_ID}.35/24
---
apiVersion: core.eda.nokia.com/v1
kind: TopoNode
metadata:
  name: g${INSTANCE_ID}-spine11
  labels:
    eda.nokia.com/role: spine
    eda.nokia.com/security-profile: managed
    containerlab: managed
    role: hackathon-infra
  namespace: eda
spec:
  nodeProfile: hackathon-srlinux-26.7.2
  npp:
    mode: normal
  operatingSystem: srl
  platform: 7220 IXR-D5
  version: 26.7.2
  productionAddress:
    ipv4: 10.128.${INSTANCE_ID}.31/24
---
apiVersion: core.eda.nokia.com/v1
kind: TopoNode
metadata:
  name: g${INSTANCE_ID}-spine12
  labels:
    eda.nokia.com/role: spine
    eda.nokia.com/security-profile: managed
    containerlab: managed
    role: hackathon-infra
  namespace: eda
spec:
  nodeProfile: hackathon-srlinux-26.7.2
  npp:
    mode: normal
  operatingSystem: srl
  platform: 7220 IXR-D5
  version: 26.7.2
  productionAddress:
    ipv4: 10.128.${INSTANCE_ID}.32/24
---
apiVersion: core.eda.nokia.com/v1
kind: TopoNode
metadata:
  name: g${INSTANCE_ID}-pe2
  labels:
    eda.nokia.com/role: backbone
    eda.nokia.com/security-profile: managed
    containerlab: managed
    role: hackathon-infra
  namespace: eda
spec:
  nodeProfile: hackathon-srlinux-26.7.2
  npp:
    mode: normal
  operatingSystem: srl
  platform: 7250 IXR-X1B
  version: 26.7.2
  productionAddress:
    ipv4: 10.128.${INSTANCE_ID}.22/24
---

# --- INTERFACES ---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine11-ethernet-1-1
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-1
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine11
  type: Interface
  mtu: 9198
  description: "inter-switch link to leaf11"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: leaf11-ethernet-1-31
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-31
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf11
  type: Interface
  mtu: 9198
  description: "inter-switch link to spine11"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine11-ethernet-1-2
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-2
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine11
  type: Interface
  mtu: 9198
  description: "inter-switch link to leaf12"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: leaf12-ethernet-1-31
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-31
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf12
  type: Interface
  mtu: 9198
  description: "inter-switch link to spine11"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine11-ethernet-1-3
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-3
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine11
  type: Interface
  mtu: 9198
  description: "inter-switch link to leaf13"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: leaf13-ethernet-1-31
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-31
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf13
  type: Interface
  mtu: 9198
  description: "inter-switch link to spine11"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine12-ethernet-1-1
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-1
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine12
  type: Interface
  mtu: 9198
  description: "inter-switch link to leaf11"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: leaf11-ethernet-1-32
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf11
  type: Interface
  mtu: 9198
  description: "inter-switch link to spine12"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine12-ethernet-1-2
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-2
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine12
  type: Interface
  mtu: 9198
  description: "inter-switch link to leaf12"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: leaf12-ethernet-1-32
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf12
  type: Interface
  mtu: 9198
  description: "inter-switch link to spine12"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine12-ethernet-1-3
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-3
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine12
  type: Interface
  mtu: 9198
  description: "inter-switch link to leaf13"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: leaf13-ethernet-1-32
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-leaf13
  type: Interface
  mtu: 9198
  description: "inter-switch link to spine12"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: pe2-ethernet-1-1
  namespace: eda
  labels:
    eda.nokia.com/role: interDC
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-1
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-pe2
  type: Interface
  description: "DCI link to pe4"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: pe2-ethernet-1-2
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-2
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-pe2
  type: Interface
  mtu: 9198
  description: "inter-switch link to spine11"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine11-ethernet-1-32
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine11
  type: Interface
  mtu: 9198
  description: "inter-switch link to pe2"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: pe2-ethernet-1-3
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  ethernet:
    stormControl:
      enabled: false
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-3
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-pe2
  type: Interface
  mtu: 9198
  description: "inter-switch link to spine12"
---
apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  name: spine12-ethernet-1-32
  namespace: eda
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
spec:
  enabled: true
  encapType: "Null"
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-32
      lacpPortPriority: 32768
      node: g${INSTANCE_ID}-spine12
  type: Interface
  mtu: 9198
  description: "inter-switch link to pe2"
---

# --- TOPOLINKS ---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
  name: spine11-e1-1-leaf11-e1-31
  namespace: eda
spec:
  links:
    - local:
        interface: ethernet-1-1
        interfaceResource: spine11-ethernet-1-1
        node: g${INSTANCE_ID}-spine11
      remote:
        interface: ethernet-1-31
        interfaceResource: leaf11-ethernet-1-31
        node: g${INSTANCE_ID}-leaf11
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
  name: spine11-e1-2-leaf12-e1-31
  namespace: eda
spec:
  links:
    - local:
        interface: ethernet-1-2
        interfaceResource: spine11-ethernet-1-2
        node: g${INSTANCE_ID}-spine11
      remote:
        interface: ethernet-1-31
        interfaceResource: leaf12-ethernet-1-31
        node: g${INSTANCE_ID}-leaf12
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
  name: spine11-e1-3-leaf13-e1-31
  namespace: eda
spec:
  links:
    - local:
        interface: ethernet-1-3
        interfaceResource: spine11-ethernet-1-3
        node: g${INSTANCE_ID}-spine11
      remote:
        interface: ethernet-1-31
        interfaceResource: leaf13-ethernet-1-31
        node: g${INSTANCE_ID}-leaf13
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
  name: spine12-e1-1-leaf11-e1-32
  namespace: eda
spec:
  links:
    - local:
        interface: ethernet-1-1
        interfaceResource: spine12-ethernet-1-1
        node: g${INSTANCE_ID}-spine12
      remote:
        interface: ethernet-1-32
        interfaceResource: leaf11-ethernet-1-32
        node: g${INSTANCE_ID}-leaf11
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
  name: spine12-e1-2-leaf12-e1-32
  namespace: eda
spec:
  links:
    - local:
        interface: ethernet-1-2
        interfaceResource: spine12-ethernet-1-2
        node: g${INSTANCE_ID}-spine12
      remote:
        interface: ethernet-1-32
        interfaceResource: leaf12-ethernet-1-32
        node: g${INSTANCE_ID}-leaf12
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
  name: spine12-e1-3-leaf13-e1-32
  namespace: eda
spec:
  links:
    - local:
        interface: ethernet-1-3
        interfaceResource: spine12-ethernet-1-3
        node: g${INSTANCE_ID}-spine12
      remote:
        interface: ethernet-1-32
        interfaceResource: leaf13-ethernet-1-32
        node: g${INSTANCE_ID}-leaf13
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
  name: spine11-e1-32-pe2-e1-2
  namespace: eda
spec:
  links:
    - local:
        interface: ethernet-1-32
        interfaceResource: spine11-ethernet-1-32
        node: g${INSTANCE_ID}-spine11
      remote:
        interface: ethernet-1-2
        interfaceResource: pe2-ethernet-1-2
        node: g${INSTANCE_ID}-pe2
      type: interSwitch
---
apiVersion: core.eda.nokia.com/v1
kind: TopoLink
metadata:
  labels:
    eda.nokia.com/role: interSwitch
    role: hackathon-infra
  name: spine12-e1-32-pe2-e1-3
  namespace: eda
spec:
  links:
    - local:
        interface: ethernet-1-32
        interfaceResource: spine12-ethernet-1-32
        node: g${INSTANCE_ID}-spine12
      remote:
        interface: ethernet-1-3
        interfaceResource: pe2-ethernet-1-3
        node: g${INSTANCE_ID}-pe2
      type: interSwitch
---

# --- MANAGEMENT ROUTER ---
# ---
# apiVersion: bootstrap.eda.nokia.com/v1alpha1
# kind: ManagementRouter
# metadata:
#   name: mgmt
#   namespace: eda
#   labels:
#     role: hackathon-infra
# spec:
#   nodeSelector:
#     - eda.nokia.com/role=leaf
#     - eda.nokia.com/role=spine

# --- EDA DISCOVERY GRPC SERVER ---
# this configlet adds eda-discovery grpc server
# so in case we need to redeploy EDA after it onboarded nodes
# and removed the discovery grpc server
# this configlet will adds it back and makes it possible to
# rediscover previously onboarded nodes
apiVersion: config.eda.nokia.com/v1
kind: Configlet
metadata:
  name: eda-discovery
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  endpointSelectors:
    - containerlab=managed
  operatingSystem: srl
  configs:
    - path: .system.grpc-server{.name=="eda-discovery"}
      operation: Create
      config: |-
        {
          "name": "eda-discovery",
          "admin-state": "enable",
          "rate-limit": 65535,
          "session-limit": 1024,
          "metadata-authentication": true,
          "default-tls-profile": true,
          "network-instance": "mgmt",
          "port": 50052,
          "services": [
            "gnmi",
            "gnsi"
          ]
        }
---

# --- EDA COMMON SYSLOG SERVER ---
# considering we don't have a way (yet) to configure a
# common syslog server, this makes sure the hackathon
# syslog server is applied on all EDA managed devices
apiVersion: config.eda.nokia.com/v1
kind: Configlet
metadata:
  name: syslog-mgmt
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  endpointSelectors:
    - containerlab=managed
  operatingSystem: srl
  configs:
    - path: .system.logging
      operation: Create
      config: |-
        {
          "network-instance": "mgmt",
          "remote-server": [
            {
              "host": "10.128.${INSTANCE_ID}.75",
              "transport": "udp",
              "remote-port": 1514,
              "facility": [
                {
                  "facility-name": "local6",
                  "priority": {
                    "match-above": "informational"
                  }
                }
              ]
            }
          ]
        }
---

# --- DEFAULT MTU ---
apiVersion: siteinfo.eda.nokia.com/v1
kind: DefaultMTU
metadata:
  name: ip-mtu
  namespace: eda
spec:
  layer3MTU: 9198
  nodeSelectors:
    - containerlab=managed