- name: Config IP Interface Ethernet 1-1 srl1
  gather_facts: false
  hosts: clab-ansible-srl1
  tasks:
    - name: Add interface
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/1]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: 1.1.1.1/30
          - path: /network-instance[name=default]
            value:
                interface: 
                  - name: ethernet-1/1.0
      register: set_response


- name: Config IP Interface Ethernet 1-1 srl2
  gather_facts: false
  hosts: clab-ansible-srl2
  tasks:
    - name: Add interface
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/1]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: 1.1.1.2/30
          - path: /network-instance[name=default]
            value:
                interface: 
                  - name: ethernet-1/1.0
      register: set_response

    

