apiVersion: core.eda.nokia.com/v1
kind: IndexAllocationPool
metadata:
  labels:
    eda.nokia.com/bootstrap: 'true'
  name: tunnel-index-pool
  namespace: eda
spec:
  publishAllocations: true
  segments:
    - allocations:
        - name: bd-macvrf1
          value: 1
        - name: bd-macvrf101
          value: 101
        - name: rtr-ipvrf201
          value: 201
      size: 4000
      start: 0
