# Copyright 2026 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: fabrics.eda.nokia.com/v1
kind: Fabric
metadata:
  name: hackathon-fabric
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  interSwitchLinks:
    linkSelectors:
      - eda.nokia.com/role=interSwitch
    unnumbered: IPv6
  leafs:
    leafNodeSelectors:
      - eda.nokia.com/role=leaf
  spines:
    spineNodeSelectors:
      - eda.nokia.com/role=spine
  borderLeafs:
    borderLeafNodeSelectors:
      - eda.nokia.com/role=backbone
  overlayProtocol:
    bgp:
      autonomousSystem: 65000
      clusterID: 10.46.${INSTANCE_ID}.22
      rrClientNodeSelectors:
        - eda.nokia.com/role=leaf
      rrIpAddresses:
        - fd00:fde8::${INSTANCE_ID}:22
    protocol: IBGP
  systemPoolIPv4: hackathon-systemipv4
  systemPoolIPv6: hackathon-systemipv6
  underlayProtocol:
    bgp:
      asnPool: hackathon-asnpool
      exportPolicies:
        - ebgp-isl-export-policy-hackathon-fabric-custom
    protocols:
      - EBGP
