apiVersion: fabrics.eda.nokia.com/v1alpha1
kind: Fabric
metadata:
  name: hackathon-fabric
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  interSwitchLinks:
    linkSelector:
      - eda.nokia.com/role=interSwitch
    unnumbered: IPV6
  leafs:
    asnPool: hackathon-asnpool
    leafNodeSelector:
      - eda.nokia.com/role=leaf
  overlayProtocol:
    bgp:
      autonomousSystem: 65000
      rrClientNodeSelector:
        - eda.nokia.com/role=leaf
      rrIPAddresses:
        - fd00:fde8::${INSTANCE_ID}:22
    protocol: IBGP
  spines:
    asnPool: hackathon-asnpool
    spineNodeSelector:
      - eda.nokia.com/role=spine
  systemPoolIPV4: hackathon-systemipv4
  systemPoolIPV6: hackathon-systemipv6
  underlayProtocol:
    bgp:
      asnPool: hackathon-asnpool
      exportPolicy:
        - ebgp-isl-export-policy-hackathon-fabric-custom
    protocol:
      - EBGP
