apiVersion: protocols.eda.nokia.com/v1
kind: DefaultBGPGroup
metadata:
  name: bgpgroup-ebgp-pe
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  exportPolicy:
    - accept-all
  importPolicy:
    - accept-all
  ipv4Unicast:
    advertiseIPV6NextHops: true
    enabled: true
    receiveIPV6NextHops: true
  ipv6Unicast:
    enabled: true
