# --- L3 INTERFACE (pe2 side of the WAN link e1-1 <-> pe4 e1-1) ---
apiVersion: routing.eda.nokia.com/v1
kind: DefaultInterface
metadata:
  labels:
    eda.nokia.com/role: interDC
    role: hackathon-infra
  name: interface-pe2-ethernet-1-1
  namespace: eda
spec:
  defaultRouter: router-g${INSTANCE_ID}-pe2
  description: DCI link to pe4
  interface: pe2-ethernet-1-1
  ipMTU: 9198
  ipv4Addresses:
    - ipPrefix: 10.64.${INSTANCE_ID}.2/31
      primary: true
  ipv6Addresses:
    - ipPrefix: fd00:fde8:0:1:${INSTANCE_ID}:22:24:2/127
      primary: true
