# --- OSPF UNDERLAY (v2 for IPv4, v3 for IPv6) ---

apiVersion: protocols.eda.nokia.com/v2
kind: DefaultOSPFArea
metadata:
  labels:
    eda.nokia.com/role: hackathon-infra
  name: wan-v4-area-0
  namespace: eda
spec:
  areaID: 0.0.0.0
  areaType: Normal
---
apiVersion: protocols.eda.nokia.com/v2
kind: DefaultOSPFArea
metadata:
  labels:
    eda.nokia.com/role: hackathon-infra
  name: wan-v6-area-0
  namespace: eda
spec:
  areaID: 0.0.0.0
  areaType: Normal
