apiVersion: services.eda.nokia.com/v1alpha1
kind: BridgeDomain
metadata:
  name: macvrf1
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  description: MAC-VRF for connectivity via the GRT of the WAN
  evi: 1
  eviPool: evi-pool
  exportTarget: target:65000:1
  importTarget: target:65000:1
  macAging: 600
  tunnelIndexPool: tunnel-index-pool
  type: EVPNVXLAN
  vni: 1
  vniPool: vni-pool
