apiVersion: services.eda.nokia.com/v1alpha1
kind: VLAN
metadata:
  name: vlan1
  namespace: eda
  labels:
    role: hackathon-infra
spec:
  bridgeDomain: macvrf1
  description: VLAN 1 for connectivity to the WAN GRT
  interfaceSelector:
    - edge-type=compute
  vlanID: "1"
  macDuplicationDetectionAction: "UseBridgeDomainAction"
