# Copyright 2023 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

name: config

topology:
  defaults:
    kind: srl
  kinds:
    vr-sros:
      image: vr-sros:23.7.R1
      license: /opt/srexperts/license-sros23.txt
    srl:
      image: ghcr.io/nokia/srlinux:latest
      type: ixrd2l
  nodes:
    sr1:
      kind: vr-sros
      ports:
        - 50000-51000:22
        - 50000-51000:57400
    sr2:
      kind: vr-sros
      ports:
        - 50000-51000:22
        - 50000-51000:57400 
    spine1:
      type: ixrd3l
      ports:
        - 50000-51000:22
        - 50000-51000:57400
    spine2:
      type: ixrd3l
      ports:
        - 50000-51000:22
        - 50000-51000:57400
    leaf1:
      ports:
        - 50000-51000:22
        - 50000-51000:57400
    leaf2:
      ports:
        - 50000-51000:22
        - 50000-51000:57400

  links:
    - endpoints:
        - "leaf1:e1-49"
        - "spine1:e1-1"
    - endpoints:
        - "leaf1:e1-50"
        - "spine2:e1-1"
    - endpoints:
        - "leaf2:e1-49"
        - "spine1:e1-2"
    - endpoints:
        - "leaf2:e1-50"
        - "spine2:e1-2"

    - endpoints:
        - "spine1:e1-3"
        - "sr1:eth1"
    - endpoints:
        - "spine1:e1-4"
        - "sr2:eth1"

    - endpoints:
        - "spine2:e1-3"
        - "sr1:eth2"
    - endpoints:
        - "spine2:e1-4"
        - "sr2:eth2"
