- name: Set ethernet-1/1 IPv4 R1
  hosts: clab-ansible-srl1
  gather_facts: false
  tasks:
  - name: Set ethernet-1/1 IPv4 R1
    nokia.srlinux.config:
      update:
      - path: /interface[name=ethernet-1/1]/subinterface[index=0]/ipv4/address[ip-prefix=1.1.1.1/30]
        value:
          ip-prefix: 1.1.1.1/32

- name: Set ethernet-1/1 IPv4 R2
  hosts: clab-ansible-srl2
  gather_facts: false
  tasks:
  - name: Set ethernet-1/1 IPv4 R2
    nokia.srlinux.config:
      update:
      - path: /interface[name=ethernet-1/1]/subinterface[index=0]/ipv4/address[ip-prefix=1.1.1.2/30]
        value:
          ip-prefix: 1.1.1.2/32
