- name: Run "show version" CLI command
  hosts: clab
  gather_facts: false
  tasks:
    - name: Run "show version" CLI command
      nokia.srlinux.cli:
        commands:
          - show version
      register: response

    - debug:
        var: response