- name: Get system information
  hosts: clab
  gather_facts: false
  tasks:
  - name: Get /system/information container
    nokia.srlinux.get:
      paths:
      - path: /system/information
        datastore: state
<<<<<<< HEAD

=======
>>>>>>> 047182086b3dac4c6760141a13ee0e9e1a48e190
