# Copyright 2023 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

version: '3'
services:
  notebook:
    image: jupyter/base-notebook:latest
    env_file: ./.env
    volumes: 
      - ./:/srexperts/:ro
    ports:
      - 8888:8888
    working_dir: "/srexperts"
    command: "start-notebook.sh /srexperts --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.autoreload=True"