{
 "title": "Syslog",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "NE",
    "query": {}
   },
   {
    "name": "Logs",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Topology - Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (count_over_time({source=~\".+\"}[30s]))",
     "legendFormat": "{{ application }}"
    }
   ]
  },
  {
   "title": "Topology - count per app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (application) (rate({source=~\".+\"}[30s]))",
     "legendFormat": "{{ application }}"
    }
   ]
  },
  {
   "title": "Syslog",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{application=~\".+\"}"
    }
   ]
  },
  {
   "title": "Node - Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (count_over_time({source=~\"(?i)$NE\"}[30s]))",
     "legendFormat": "{{ application }}"
    }
   ]
  },
  {
   "title": "Node - count per app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (application) (rate({source=\"$NE\"}[30s]))",
     "legendFormat": "{{ application }}"
    }
   ]
  },
  {
   "title": "Syslog - per node",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{application=~\".+\", source=\"$NE\"}"
    }
   ]
  },
  {
   "title": "Syslog - per app",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{application=\"$Logs\", source=\"$NE\"}"
    }
   ]
  }
 ]
}